#!/bin/bash

VM=$1
SAGE_SOURCE=$2
VMSSH=root@localhost
VMPORT=2555

./vm/start-vm $VM $VMPORT

source ./vm/install-sagecell-functions

remove_install_log
update_system
kill_monitor
remove_accounts
set_up_sageserver_account
upload_sage_source
install_sage
RC=`grep "Error building Sage" install.log` 
if [ "$RC" != "" ]; then
   echo "Error building Sage!"
   exit 1
fi
install_sagecell

copy_database_system_files
set_up_database_firewall
change_hostname database
virsh shutdown $VM

