#!/bin/bash

set -v
# These variable names are important for the functions below
VM=$1
SAGE_SOURCE=$2
VMSSH=root@localhost
VMPORT=2555

./vm/start-vm $VM $VMPORT

source ./vm/install-sagecell-functions

remove_install_log
update_system
kill_monitor
remove_accounts
set_up_sageserver_account
set_up_sageworker_account
make_tmp_dir
upload_sage_source
install_sage
RC=`grep "Error building Sage" install.log` 
if [ "$RC" != "" ]; then
   echo "Error building Sage!"
   exit 1
fi
install_sagecell
install_extra_python_packages
copy_sagecell_system_files
lock_down_sageworker
set_up_sagecell_firewall
#compress_zero
virsh shutdown $VM
