#!/bin/sh

# ./mnt should point to the CentOS DVD
rm centos.img
qemu-img create -f qcow2 centos.img 20G

virsh destroy centos-vm
virsh undefine centos-vm

virt-install --name centos-vm \
--ram 8192 \
--network user,model=virtio \
--cpu host \
--vcpus=14 \
--disk path=centos.img,device=disk,bus=virtio,format=qcow2,cache=writeback,size=25  \
--location mnt \
--initrd-inject=vm/base-centos.kickstart \
--os-type linux \
--os-variant rhel6 \
--accelerate \
--nographics \
--noreboot \
--extra-args="cmdline ks=file:/base-centos.kickstart console=ttyS0"
#--noautoconsole \

