#!/bin/sh

BASE=$1
NAME=$2

if virsh --connect qemu:///session shutdown $BASE; then
    sleep 10
fi
virsh --connect qemu:///session destroy $NAME
virsh --connect qemu:///session undefine $NAME

qemu-img create -b $BASE.img -f qcow2 $NAME.img
virt-install --connect qemu:///session \
 --name $NAME \
 --ram 8192 \
 --vcpus=4 \
 --network user,model=virtio \
 --cpu host \
 --import \
 --disk path=$NAME.img,device=disk,bus=virtio,format=qcow2,cache=writeback \
 --os-type linux \
 --os-variant rhel6 \
 --noautoconsole \
 --nographics
