#!/bin/sh

rm centos.img
qemu-img create -f qcow2 centos.img 20G

virsh destroy centos-vm
virsh undefine centos-vm

virt-install --name centos-vm \
--ram 8192 \
--network user,model=virtio \
--cpu host \
--vcpus=12 \
--disk path=centos.img,device=disk,bus=virtio,format=qcow2,cache=writeback,size=20  \
--location mnt \
--initrd-inject=sagecell-ks.cfg \
--os-type linux \
--os-variant rhel6 \
--accelerate \
--nographics \
--noreboot \
--extra-args="cmdline ks=file:/sagecell-ks.cfg console=ttyS0"
#--noautoconsole \

virsh qemu-monitor-command centos-vm --hmp 'hostfwd_add ::5456-:22'
