#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o xtrace

# ./make-base-centos NEW_VM_NAME LOCATION_OF_ISO_MOUNT

VM=$1
ISO=$2
LOCATION=mnt
SIZE=25

rm -f $VM.img
qemu-img create -f qcow2 $VM.img ${SIZE}G

virsh destroy $VM || true
virsh undefine $VM || true

fuseiso -p $ISO $LOCATION
# rootpassword is a file that looks like:
# rootpw --iscrypted <CRYPTED PASSWORD>
sed -e "/ROOTPASSWORD/r rootpassword" -e "/ROOTPASSWORD/d"  < vm/base-centos.kickstart-template > base-centos.kickstart
chmod go-rwx base-centos.kickstart

virt-install --name=$VM \
--ram=8192 \
--vcpus=14 \
--network user,model=virtio \
--cpu host \
--disk path=$VM.img,device=disk,bus=virtio,format=qcow2,cache=writeback,size=$SIZE  \
--os-type=linux \
--os-variant=rhel6 \
--accelerate \
--nographics \
--noreboot \
--location $LOCATION \
--initrd-inject=base-centos.kickstart \
--extra-args="cmdline ks=file:/base-centos.kickstart console=ttyS0"
#--noautoconsole \

fusermount -u $LOCATION

