#!/bin/sh

BASE=$1
NAME=$2

if virsh shutdown $BASE; then
    sleep 10
fi
virsh destroy $NAME
virsh undefine $NAME

rm -f $NAME.img
qemu-img create -b $BASE.img -f qcow2 $NAME.img
virt-install \
 --name $NAME \
 --ram=8192 \
 --vcpus=4 \
 --network user,model=virtio \
 --cpu host \
 --import \
 --disk path=$NAME.img,device=disk,bus=virtio,format=qcow2,cache=writeback \
 --os-type=linux \
 --os-variant=rhel6 \
 --noautoconsole \
 --nographics
