#!/bin/sh

rm centos.img
qemu-img create -f qcow2 centos.img 20G

virt-install --name centos-vm \
--ram 4096 \
--network user,model=virtio \
--cpu host \
--vcpus=1 \
--disk path=centos.img,device=disk,bus=virtio,format=qcow2,cache=writeback,size=20  \
--location mnt \
--initrd-inject=sagecell-ks.cfg \
--os-type linux \
--os-variant rhel6 \
--accelerate \
--nographics \
--extra-args="cmdline ks=file:/sagecell-ks.cfg console=ttyS0"
