#!/bin/bash
set -o errexit
set -o nounset
#set -o xtrace

VM=$1
SSHPORT=$2
VIRSH="virsh --connect=qemu:///session"

if [[ `$VIRSH domstate $VM` != "running" ]]; then
    if ! $VIRSH start $VM; then
       echo "Failed to start $VM!"
       exit 1
    fi
    echo "Booting $VM"
    sleep 30
fi

./vm/forward-port $VM $SSHPORT 22
while [[ `ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -i sagecell_rsa -p $SSHPORT echo "ready"` != "ready" ]]; do
    echo "Waiting for $VM to start."
    sleep 5
done
