#!/bin/sh

#set -v
VM=$1
SSHPORT=$2

STATUS=`virsh dominfo $VM | grep 'State:.*running'`
if [ $? -ne 0 ]; then
    virsh start $VM
    if [ $? -ne 0 ]; then
       echo "Failed to start virtual machine!"
       exit 1
    fi
    STATUS="booting"
    echo "Booting $VM"
    sleep 2
fi

sleep 3

./vm/forward-port $VM $SSHPORT 22
STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
while [ "$STATUS" != "ready" ]; do
    echo "Waiting for VM to start."
    sleep 5
    STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
done
