#!/bin/sh

#set -v
VM=$1
SSHPORT=$2
WEBPORT=$3

STATUS=`virsh dominfo $VM | grep 'State:.*running'`
if [ $? -ne 0 ]; then
    virsh start $VM
    if [ $? -ne 0 ]; then
       echo "Failed to start virtual machine!"
       exit 1
    fi
    STATUS="booting"
    echo "Booting $VM"
    sleep 2
fi

virsh qemu-monitor-command $VM --hmp "hostfwd_add ::$SSHPORT-:22"
virsh qemu-monitor-command $VM --hmp "hostfwd_add ::$WEBPORT-:8888"
STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
while [ "$STATUS" != "ready" ]; do
    echo "Waiting for VM to start."
    sleep 5
    STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
done
