#!/usr/bin/env bash
set -o errexit
#set -o nounset
#set -o xtrace

# stop VM_NAME [REMOTELOGIN]

VIRSH="virsh --connect qemu:///session"

if [ -n "$2" ]; then
    SSH="ssh $2"
fi
if [[ "`$SSH $VIRSH domstate $1`" == "running" ]]; then
    $SSH $VIRSH shutdown $1
    while [[ "`$SSH $VIRSH domstate $1`" != "shut off" ]]; do
        echo -n .
        sleep 1
    done
fi

