#!/bin/bash

set PATH=$SAGE_VENV/bin:$PATH

WORKER=worker
WORKER_USER=sc_work

printf "Keygen ... "
sudo -E -H -u $WORKER_USER ssh-keygen -t ed25519 -N '' -f /home/$WORKER_USER/.ssh/id_ed25519 -q
cp -p /home/$WORKER_USER/.ssh/*.pub /pubkey/$WORKER.pub
printf "done\n"

until ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no \
      -o ConnectTimeout=2 $WORKER_USER@$WORKER 'echo connected'; do
    echo "Waiting for $WORKER SSH ..." >&2
    sleep 2
done

printf "Keyscan ... "
ssh-keyscan -H $WORKER 2>/dev/null >> ~/.ssh/known_hosts
printf "done\n"

printf "Web server config ... "
cp config_default.py config.py
sed -i "/\"host\"/ s/localhost/$WORKER/" config.py
sed -i "/\"username\"/ s/None/\"$WORKER_USER\"/" config.py
printf "done\n"

printf "Rsyslog config ... "
sudo sed -i '/kernel/ d' /etc/rsyslog.conf || exit 1
sudo /usr/sbin/rsyslogd -n &
printf "done\n"

sage web_server.py

