#!/bin/sh

# Wrap a JavaScript file with a function that gives it the Sage Cell's version
# of jQuery

echo "(function (jQuery, \$, IPython) {"
cat $1
echo "}(sagecell.jQuery, sagecell.jQuery, IPython));"
