#!/usr/bin/env bash

iptables --flush INPUT
# Loopback traffic
iptables -A INPUT -i lo -j ACCEPT
# Established connections
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# Incoming connections to SageCell server for computations
iptables -A INPUT -p tcp --dport 8888 -j ACCEPT
# Incoming connections to nginx for static content
iptables -A INPUT -p tcp --dport 8889 -j ACCEPT
# And nothing else, including SSH!
iptables -P INPUT DROP
