#!/usr/bin/env bash

ipset create allowed hash:net
ipset add allowed 130.211.113.153   # Permalinks
ipset add allowed 91.189.88.0/24    # Canonical Group Limited, archive.ubuntu.com
ipset add allowed 128.174.0.0/16    # University of Illinois, Macaulay2
ipset add allowed 140.82.112.0/20   # GitHub, github.com
ipset add allowed 185.199.108.0/22   # GitHub, raw.githubusercontent.com


iptables --flush
# Loopback traffic
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
# Established connections
iptables -A INPUT  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Outbound DHCP request
iptables -A OUTPUT -p udp --dport 67:68 --sport 67:68 -j ACCEPT
# Outbound DNS lookups
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
# Outbound Network Time Protocol (NTP) requests
iptables -A OUTPUT -p udp --dport 123 --sport 123 -j ACCEPT

# Incoming connections to SageCell server for computations
iptables -A INPUT -p tcp --dport 8888 -j ACCEPT
# Incoming connections to nginx for static content
iptables -A INPUT -p tcp --dport 8889 -j ACCEPT

# Outbound HTTP to allowed hosts
iptables -A OUTPUT -p tcp -m multiport --dport http,https -m state --state NEW -m set --match-set allowed dst -j ACCEPT

# And nothing else
iptables -P INPUT  DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
