#!/bin/sh
ROOT=/home/sagenb/sagecell
cd ${ROOT}
echo Killing webserver 
screen -S sagecell-web -p 0 -X stuff 
sleep 3
screen -S sagecell-web -p 0 -X stuff 
sleep 3
ssh sagenbws@localhost "ps aux | grep sagecell | cut -c10-15 | xargs kill"
ps aux | grep sagecell | grep screen | cut -c10-15| xargs kill
rm -rf ${ROOT}/router-*.ipc

echo "Checking screen sessions terminated"
screen -ls | grep -q sagecell-web
if [ $? -eq 0 -o $? -eq 2 ]; then
   echo $i not terminated or there is another error terminating
   exit 1
fi
echo All screen sessions terminated

#Exit if any argument is supplied
if [ "$1" ]; then
    exit 1
fi

sage/sage -sh -c "make -C sagecell -B"
echo starting web
screen -c ${ROOT}/screen-config-web -d -m -S sagecell-web ./start 5469
