#!/bin/sh


# for health check, following the ideas in http://www.igvita.com/2008/12/02/zero-downtime-restarts-with-haproxy/

case "$1" in
    on)
     /sbin/iptables -t nat --flush PREROUTING
     /sbin/iptables -t nat -A PREROUTING -p tcp --dport 9888 -j REDIRECT --to-ports 8888
     # don't save so reboots require reenabling health check redirect
     echo 'ENABLING health check on port 9888'
     ;;
    off)
     /sbin/iptables -t nat --flush PREROUTING
     echo 'DISABLING health check on port 9888'
     ;;
    status)
     # exit status 0---health enabled
     # exit status 1---health disabled
     # from http://superuser.com/questions/360094/how-can-i-check-if-an-iptables-rule-already-exists
     # we should switch to using iptables -C when we upgrade to a newer iptables (maybe in centos 7)
     /sbin/iptables-save | /bin/grep -q -- '-A PREROUTING -p tcp -m tcp --dport 9888 -j REDIRECT --to-ports 8888'
     ;;
esac
