#!/bin/sh


# for health check, following the ideas in http://www.igvita.com/2008/12/02/zero-downtime-restarts-with-haproxy/

case "$1" in
    on)
     iptables -t nat --flush PREROUTING
     iptables -t nat -A PREROUTING -p tcp --dport 9888 -j REDIRECT --to-ports 888
88
     # don't save so reboots require reenabling health check redirect
     echo 'ENABLING health check on port 9888'
     ;;
    off)
     iptables -t nat --flush PREROUTING
     echo 'DISABLING health check on port 9888'
esac
